//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.28 at 11:21:17 AM EEST 
//


package lt.jmarkus.soap.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the lt.jmarkus.soap.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: lt.jmarkus.soap.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListValidateResponse }
     * 
     */
    public ListValidateResponse createListValidateResponse() {
        return new ListValidateResponse();
    }

    /**
     * Create an instance of {@link ListValidateResponse.ValidityMap }
     * 
     */
    public ListValidateResponse.ValidityMap createListValidateResponseValidityMap() {
        return new ListValidateResponse.ValidityMap();
    }

    /**
     * Create an instance of {@link GetValidateResponse }
     * 
     */
    public GetValidateResponse createGetValidateResponse() {
        return new GetValidateResponse();
    }

    /**
     * Create an instance of {@link GetValidateRequest }
     * 
     */
    public GetValidateRequest createGetValidateRequest() {
        return new GetValidateRequest();
    }

    /**
     * Create an instance of {@link ListValidateRequest }
     * 
     */
    public ListValidateRequest createListValidateRequest() {
        return new ListValidateRequest();
    }

    /**
     * Create an instance of {@link Number }
     * 
     */
    public Number createNumber() {
        return new Number();
    }

    /**
     * Create an instance of {@link ListValidateResponse.ValidityMap.Entry }
     * 
     */
    public ListValidateResponse.ValidityMap.Entry createListValidateResponseValidityMapEntry() {
        return new ListValidateResponse.ValidityMap.Entry();
    }

}
